# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pose_pb2 as pose__pb2


class PoseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKeypoints = channel.unary_unary(
                '/Pose/GetKeypoints',
                request_serializer=pose__pb2.Image.SerializeToString,
                response_deserializer=pose__pb2.Keypoints.FromString,
                )


class PoseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKeypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKeypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeypoints,
                    request_deserializer=pose__pb2.Image.FromString,
                    response_serializer=pose__pb2.Keypoints.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pose', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pose(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKeypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pose/GetKeypoints',
            pose__pb2.Image.SerializeToString,
            pose__pb2.Keypoints.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
